using System;
using System.Threading.Tasks;
using DelegatesEventsContainerTest05.Service;

namespace DelegatesEventsContainerTest05
{
    /*
     * PokemonServiceFactory is injected which is auto-generated by Unity Container.
     * Every time PokemonService is created it creates new HttpClient instance.
     * https://autofaccn.readthedocs.io/en/latest/resolve/relationships.html
     */
    public class Worker : IWorker
    {
        private readonly Func<IPokemonService> _pokemonServiceFactory;

        public Worker(Func<IPokemonService> pokemonServiceFactory)
        {
            _pokemonServiceFactory = pokemonServiceFactory;
            Console.WriteLine("PokemonServiceFactory Hash:" + _pokemonServiceFactory.GetHashCode());
        }

        public async Task DoWork()
        {
            int pokeCount = 5;

            using (var pokemonService = _pokemonServiceFactory())
            {
                Console.WriteLine("PokemonService Hash:" + pokemonService.GetHashCode());

                for (int i = 1; i <= pokeCount; i++)
                {
                    var pokemon = await pokemonService.GetPokemonAsync("https://pokeapi.co/api/v2/pokemon/" + i);
                    Console.WriteLine(pokemon.Name);
                }
            }
        }
    }
}
